const data = [
  {
    id: 15,
    name: "2 Cool 4 Skool",
    releaseDate: "2013-06-12",
    imgUrl: "https://www.generasia.com/w/images/2/2f/2_Cool_4_Skool.jpg",
    info: [
      `"2 COOL 4 SKOOL" is BTS' debut single. The song "No More Dream" was used as the lead track and "We are bulletproof PT.2" as the follow-up song. It debuted at #19 on Gaon charts and peaked at #5 on its seventh week.`,
    ],
    tracklist: [
      "1: Intro: 2 COOL 4 SKOOL (feat. DJ Friz)",
      "2: We are bulletproof PT.2",
      "3: Skit: Circle room talk",
      "4: No More Dream",
      "5: Interlude",
      "6: Johayo / Like (좋아요; Good)",
      "7: Outro: Circle room cypher",
      "8: Skit: On the Start Line (Hidden Track)",
      "9: Gil / Path (길; Path) (Hidden Track)",
    ],
  },
  {
    id: 10,
    name: "Skool Luv Affair",
    releaseDate: "2014-02-12",
    imgUrl: "https://www.generasia.com/w/images/8/88/Skool_Luv_Affair.jpg",
    info: [
      `SKOOL LUV AFFAIR is BTS' second mini-album. "Sangnamja (Boy In Luv)" was used as the lead track and "Haruman" was used as a follow-up track.`,
      `The mini-album debuted at #3 on the Gaon Album Charts, and it peaked at #1 on its 11th week. In Japan, the album charted for #13 weeks and sold 9,080 copies according to Oricon Album Charts.`,
    ],
    tracklist: [
      "1: Intro: Skool Luv Affair",
      "2: Sangnamja (Boy In Luv) / Boy In Luv (상남자; Most Masculine Man)",
      "3: Skit: Soulmate",
      "4: Eodieseo Watneunji / Where You From (어디에서 왔는지; Where Did You Come From)",
      "5: Haruman / Just One Day (하루만; Just One Day)",
      "6: Tomorrow",
      "7: BTS Cypher Pt. 2: Triptych",
      "8: Deunggor Beureikeo / Spine Breaker (등골 브레이커; Spine Breaker)",
      "9: JUMP",
      "10: Outro: Propose",
    ],
  },
  {
    id: 1,
    name: "DARK & WILD",
    releaseDate: "2014-08-20",
    imgUrl: "https://www.generasia.com/w/images/6/66/BTS_-_DARK_%26_WILD.jpg",
    info: [
      `DARK & WILD is BTS' first full-length album. The song 'Danger' was used as the lead track. It debuted and peaked at #2 on the Gaon charts and it was their first Korean release to chart on the Japanese Oricon charts.`,
      `On March 18th, 2015, a Japanese version of the album was released. It included an extra DVD with music videos and a photo gallery. It peaked at #78 on Oricon and charted for one week.`,
    ],
    tracklist: [
      "1: Intro: What am I to you",
      "2: Danger",
      "3: Hormone Jeonjaeng / War of Hormone (호르몬전쟁; Hormone War)",
      "4: Hip Hop Seongaeja / Hip Hop Phile (힙합성애자; Hip Hop Lover)",
      "5: Let Me Know",
      "6: Rain",
      "7: BTS Cypher PT.3: KILLER (ft. Supreme Boi)",
      "8: Interlude: Mwohae / Interlude: What are you doing now (뭐해; What Are You Doing)",
      "9: Haendeupon Jom Kkeojullae / Could you turn off your cell phone (핸드폰 좀 꺼줄래; Can You Turn Off Your Phone)",
      "10: Ibulkik / Embarrassed (이불킥; Blanket Kick)",
      "11: 24/7=heaven",
      "12: Yeogibwa / Look Here (여기봐; Look Here)",
      "13: 2 Haknyeon / 2nd Grade (2학년; Second Grade)",
      "14: Outro: Geuge Mari Dwae? / Outro: Do you think it makes sense? (그게 말이 돼?; Does That Make Sense?)",
    ],
  },
  {
    id: 11,
    name: "Hwayang Yeonhwa pt. 1 (화양연화)",
    releaseDate: "2015-04-29",
    imgUrl:
      "https://www.generasia.com/w/images/b/b9/BTS_-_Hwayang_Yeonhwa_white.jpg",
    info: [
      `Hwayang Yeonhwa pt. 1 is BTS' third mini-album. "I NEED U" was used as the lead track and "Jjeoreo" as the follow-up track.`,
    ],
    version: "white",
    tracklist: [
      "1: Intro: Hwayang Yeonhwa / The most beautiful moment in life (화양연화)",
      "2: I NEED U",
      "3: Jabajwo (Hold Me Tight) / Hold Me Tight (잡아줘; Catch Me)",
      "4: SKIT: Expectation!",
      "5: Jjeoreo / DOPE (쩔어; Best)",
      "6: Heungtan Sonyeondan / Boyz with Fun (흥탄소년단; BTS Diss)",
      "7: Converse High",
      "8: Isa / Moving On (이사; Move)",
      "9: Outro: Love Is Not Over",
    ],
  },
  {
    id: 12,
    name: "Hwayang Yeonhwa pt. 2 (화양연화)",
    releaseDate: "2015-11-20",
    imgUrl: "https://m.media-amazon.com/images/I/31TecRKfrFL.jpg",
    info: [
      `Hwayang Yeonhwa pt.2 is BTS' fourth mini-album. "RUN" was used as the lead track. All of the tracks charted individually on the Gaon Digital Charts, their first album to achieve so.`,
    ],
    version: "peach",
    tracklist: [
      "1: INTRO: Never Mind",
      "2: RUN",
      "3: Butterfly",
      "4: Whalien 52",
      "5: Ma City",
      "6: Baepsae / Silver Spoon (뱁새)",
      "7: SKIT: One night in a strange city",
      "8: Goyeop / Autumn Leaves (고엽; Dead Leaves)",
      "9: OUTRO: House Of Cards",
    ],
  },
  {
    id: 2,
    name: "WINGS",
    releaseDate: "2016-10-10",
    imgUrl: "https://www.generasia.com/w/images/d/dd/BTS_-_WINGS.jpg",
    info: [
      `WINGS is BTS's second full-length album. The song "Pi, Ttam, Nunmul" was used as the lead track. It was released in four versions: W, I, N and G. The overall theme of the album was inspired by Hermann Hesse's "Demian", which deals with temptation and growth. WINGS is their first album to achieve #1 on the Gaon Yearly Charts.`,
      `A Japanese version of the album, titled WINGS (Japanese Edition), was released on March 2017. This version included an extra DVD. It peaked at #57 on Oricon charts and charted for five weeks.`,
    ],
    version: "N",
    tracklist: [
      "1: Intro: Boy Meets Evil",
      "2: Pi, Ttam, Nunmul / Blood Sweat & Tears (피, 땀, 눈물, Blood, Sweat, Tears)",
      "3: Begin",
      "4: Lie",
      "5: Stigma",
      "6: First Love",
      "7: Reflection",
      "8: MAMA",
      "9: Awake",
      "10: Lost",
      "11: BTS Cypher 4",
      "12: Am I Wrong",
      "13: 21 Segi Sonyeo / 21st Century Girls (21 세기 소녀, 21st Century Girls)",
      "14: Dul! Set! (Geuraedo Joeun Nari Deo Mankireul) / 2! 3! (둘! 셋! (그래도 좋은 날이 더 많기를), Two! Three! (Still Wishing There Will Be Better Days))",
      "15: Interlude: Wings",
    ],
  },
  {
    id: 5,
    name: "YOU NEVER WALK ALONE (Compilation)",
    releaseDate: "2017-02-13",
    imgUrl:
      "https://www.generasia.com/w/images/9/95/BTS_You_Never_Walk_Alone_Left.jpg",
    info: [
      `YOU NEVER WALK ALONE is an album released by BTS. It is considered to be a repackaged version of their previously released album WINGS. The song "Bonmal" was used as the lead track.`,
    ],
    version: "Left",
    tracklist: [
      "1: Intro: Boy Meets Evil",
      "2: Pi, Ttam, Nunmul / Blood Sweat & Tears (피, 땀, 눈물, Blood, Sweat, Tears)",
      "3: Begin",
      "4: Lie",
      "5: Stigma",
      "6: First Love",
      "7: Reflection",
      "8: MAMA",
      "9: Awake",
      "10: Lost",
      "11: BTS Cypher 4",
      "12: Am I Wrong",
      "13: 21 Segi Sonyeo / 21st Century Girls (21 세기 소녀, 21st Century Girls)",
      "14: Dul! Set! (Geuraedo Joeun Nari Deo Mankireul) / 2! 3! (둘! 셋! (그래도 좋은 날이 더 많기를), Two! Three! (Still Wishing There Will Be Better Days))",
      "15: Bomnal / Spring Day (봄날, Springtime)",
      "16: Not Today",
      "17: Outro: Wings",
      "18: A Supplementary Story: You Never Walk Alone",
    ],
  },
  {
    id: 6,
    name: "YOU NEVER WALK ALONE (Compilation)",
    releaseDate: "2017-02-13",
    imgUrl:
      "https://www.generasia.com/w/images/b/bd/BTS_You_Never_Walk_Alone_Right.jpg",
    info: [
      `YOU NEVER WALK ALONE is an album released by BTS. It is considered to be a repackaged version of their previously released album WINGS. The song "Bonmal" was used as the lead track.`,
    ],
    version: "Right",
    tracklist: [
      "1: Intro: Boy Meets Evil",
      "2: Pi, Ttam, Nunmul / Blood Sweat & Tears (피, 땀, 눈물, Blood, Sweat, Tears)",
      "3: Begin",
      "4: Lie",
      "5: Stigma",
      "6: First Love",
      "7: Reflection",
      "8: MAMA",
      "9: Awake",
      "10: Lost",
      "11: BTS Cypher 4",
      "12: Am I Wrong",
      "13: 21 Segi Sonyeo / 21st Century Girls (21 세기 소녀, 21st Century Girls)",
      "14: Dul! Set! (Geuraedo Joeun Nari Deo Mankireul) / 2! 3! (둘! 셋! (그래도 좋은 날이 더 많기를), Two! Three! (Still Wishing There Will Be Better Days))",
      "15: Bomnal / Spring Day (봄날, Springtime)",
      "16: Not Today",
      "17: Outro: Wings",
      "18: A Supplementary Story: You Never Walk Alone",
    ],
  },
  {
    id: 13,
    name: "Love Yourself Seung 'Her' (承 Explanation)",
    releaseDate: "2017-09-18",
    imgUrl:
      "https://www.generasia.com/w/images/9/93/BTS_-_Love_Yourself_Her.jpg",
    info: [
      `Love Yourself Seung 'Her' is the fifth mini-album released by BTS, and the first part of the "Love Yourself" trilogy. The physical edition had two extra hidden tracks. The song "DNA" was used as the lead track.`,
    ],
    version: "E",
    extra: "veio com capa errada: V",
    tracklist: [
      "1: Intro: Serendipity",
      "2: DNA",
      "3: Best Of Me",
      "4: Bojogae / Dimple (보조개; Dimple)",
      "5: Pied Piper",
      "6: Skit: Billboard Music Awards Speech",
      "7: MIC Drop",
      "8: Gominboda Go / Go Go (고민보다 Go; Worry)",
      "9: Outro: Her",
      "10: Skit: Mangseorimgwa Duryeoum (망설임과 두려움; Hesitation and Fear) (Bonus Track)",
      "11: Bada (바다; Sea) (Bonus Hidden Track)",
    ],
  },
  {
    id: 3,
    name: "Love Yourself Jeon 'Tear' (轉 Twist)",
    releaseDate: "2018-05-18",
    imgUrl:
      "https://www.generasia.com/w/images/1/18/BTS_-_Love_Yourself_Tear.jpg",
    info: [
      `LOVE YOURSELF Jeon 'Tear' is the fourth full-length album released by BTS, and the second part of the "Love Yourself" trilogy. The song "FAKE LOVE" was used as the lead track.`,
      `Despite being a Korean release, the album is certified Gold by RIAJ for shipment of 100,000 copies.`,
    ],
    version: "Y",
    extra: "perdi cd...",
    tracklist: [
      "1: Intro : Singularity",
      "2: FAKE LOVE",
      "3: Jeonhaji Mothan Jinsim / The Truth Untold (Feat. Steve Aoki) (전하지 못한 진심; The untold truth)",
      "4: 134340",
      "5: Nagwon / Paradise (낙원; Paradise)",
      "6: Love Maze",
      "7: Magic Shop",
      "8: Airplane pt.2",
      "9: Anpanman",
      "10: So What",
      "11: Outro : Tear",
    ],
  },
  {
    id: 7,
    name: "Love Yourself Gyeol 'Answer' (結 Conclusion)",
    releaseDate: "2018-08-24",
    imgUrl:
      "https://www.generasia.com/w/images/3/39/BTS_-_Love_Yourself_Answer.jpg",
    info: [
      `Love Yourself Gyeol 'Answer' is the fifth full-length album released by BTS, and the final part of the "Love Yourself" trilogy. The song "IDOL" was used as the lead track.`,
      `Despite being a Korean release, the album ranked #1 on the Oricon weekly albums chart and is certified Gold by RIAJ for shipment of 100,000 copies.`,
    ],
    version: "S",
    tracklist: [
      "Disc 1:",
      "1: Euphoria",
      "2: Trivia Gi: Just Dance (起; Beginning)",
      "3: Serendipity (Full Length Edition)",
      "4: DNA",
      "5: Bojogae (보조개; Dimple)",
      "6: Trivia Seung: Love (承; Explanation)",
      "7: Her",
      "8: Singularity",
      "9: FAKE LOVE",
      "10: Jeonhaji Mothan Jinsim (Feat. Steve Aoki) (전하지 못한 진심; The Truth Untold)",
      "11: Trivia Jeon: Seesaw (轉; Twist)",
      "12: Tear",
      "13: Epiphany",
      "14: I'm Fine",
      "15: IDOL",
      "16: Answer: Love Myself",
      "Disc 2:",
      "1: Magic Shop",
      "2: Best Of Me",
      "3: Airplane pt.2",
      "4: Gominboda Go (고민보다 Go; Worry)",
      "5: Anpanman",
      "6: MIC Drop",
      "7: DNA (Pedal 2 LA Mix)",
      "8: FAKE LOVE (Rocking Vibe Mix)",
      "9: MIC Drop (Steve Aoki Remix) [Full Length Edition]",
      "10: IDOL (Feat. Nicki Minaj) (Digital Edition only)",
    ],
  },
  {
    id: 14,
    name: "MAP OF THE SOUL: PERSONA",
    releaseDate: "2019-04-12",
    imgUrl:
      "https://www.generasia.com/w/images/a/a5/BTS_-_MAP_OF_THE_SOUL_PERSONA_digital.jpg",
    info: [
      `MAP OF THE SOUL: PERSONA is the fifth mini-album released by BTS. The song "Jageun Geotdeureul Wihan Si (Boy With Luv)" was used as the lead track.`,
    ],
    version: "03",
    tracklist: [
      "1: Intro: Persona",
      "2: Jageun Geotdeureul Wihan Si (Boy with Luv) feat. Halsey (작은 것들을 위한 시)",
      "3: Souju (Mikrokosmos) (소우주; Microcosm)",
      "4: Make It Right",
      "5: HOME",
      "6: Jamais Vu ((Fr): Never Seen)",
      "7: Dionysus",
    ],
  },
  {
    id: 8,
    name: "BTS WORLD OST (Video Game Original Soundtrack)",
    releaseDate: "2019-06-28",
    imgUrl: "https://www.generasia.com/w/images/7/77/BTS_WORLD_OST_Cover.jpg",
    info: [
      `BTS WORLD OST is an album released by BTS. It's the soundtrack album for their mobile game "BTS WORLD".`,
    ],
    tracklist: [
      "1: Heartbeat",
      "2: Dream Glow (with Charli XCX)",
      "3: A Brand New Day (with Zara Larsson)",
      "4: All Night (with Juice WRLD)",
      "5: Captain (Namjun Theme)",
      "6: Cake Waltz (Jimin Theme)",
      "7: Shine (Yunki Theme)",
      "8: Not Alone (Jeongguk Theme)",
      "9: Friends (Hoseok Theme)",
      "10: Wish (Seok Jin Theme)",
      "11: Flying (Taehyung Theme)",
      "12: LaLaLa - Okdal (Digital Edition only)",
      "13: You Are Here - Lee Hyun (Digital Edition only)",
      "14: You Are Here (Instrumental) (Digital Edition only)",
    ],
  },
  {
    id: 4,
    name: "Map of the Soul: 7",
    releaseDate: "2020-02-21",
    imgUrl:
      "https://www.generasia.com/w/images/9/9a/BTS_-_Map_of_the_Soul_7.jpg",
    info: [
      `MAP OF THE SOUL: 7 is the sixth full-length album released by BTS, and the second part of the "Map of the Soul" trilogy. It was awarded the quadruple million certification by Gaon Chart, the first album to pass this threshold, becoming the best-selling album in South Korea. The song "Black Swan" was the first to be released on digital platforms, but the song "ON" was used as the lead track.`,
      `MAP OF THE SOUL: 7 was the most sold album in Korean history, certified 4xMillion by Gaon for over 4,000,000 sales. It was also the most sold album of 2020, with more than 6,5 million sales.`,
    ],
    version: "01",
    tracklist: [
      "1: Intro: Persona",
      "2: Jageun Geotdeureul Wihan Si (Boy with Luv) (Feat. Halsey) (작은 것들을 위한 시)",
      "3: Make It Right",
      "4: Jamais Vu (Fr: Never Seen)",
      "5: Dionysus",
      "6: Interlude: Shadow",
      "7: Black Swan",
      "8: Filter",
      "9: Sicha (My Time) (시차; Parallax)",
      "10: Louder than bombs",
      "11: ON",
      "12: UGH! (욱)",
      "13: 00:00 (Zero O'Clock)",
      "14: Inner Child",
      "15: Chingu (친구; Friend)",
      "16: Moon",
      "17: Respect",
      "18: We are Bulletproof: the Eternal",
      "19: Outro: Ego",
      "20: ON (Feat. Sia)",
    ],
  },
  {
    id: 9,
    name: "BE (Deluxe Edition) (Special Album)",
    releaseDate: "2020-11-20",
    imgUrl: "https://www.generasia.com/w/images/7/7d/BTS_BE.jpg",
    info: [
      `BE is an album released by BTS. It is considered a special album, not following the continuity of their previous album MAP OF THE SOUL: 7. It is the first album in which the members were actively involved in the preparation process. "Life Goes On" was used as the title track. Only a "Deluxe Edition" of the album was released, which includes a photobook, a making book, a lyric paper, a poster and several photos.`,
      `A more affordable "Essential Edition" was released on February 19, 2021, which is half the price of the Deluxe Edition. The package includes a CD, a 140-page photobook, 7 photo cards, 1 out of 8 random photo cards, and a poster.`,
    ],
    tracklist: [
      "1: Life Goes On",
      "2: Nae Bangeul Yeohaenghaneun Beob / Fly To My Room (내 방을 여행하는 법)",
      "3: Blue & Grey",
      "4: Skit",
      "5: Jamsi / Telepathy (잠시)",
      "6: Byeong / Dis-ease (병)",
      "7: Stay",
      "8: Dynamite",
    ],
  },
];

export default data;
