const data = [
  {
    id: 1,
    name: "DARK & WILD",
    releaseDate: "2014-08-20",
    imgUrl: "https://www.generasia.com/w/images/6/66/BTS_-_DARK_%26_WILD.jpg",
    info: [
      `DARK & WILD is BTS' first full-length album. The song 'Danger' was used as the lead track. It debuted and peaked at #2 on the Gaon charts and it was their first Korean release to chart on the Japanese Oricon charts.`,
      `On March 18th, 2015, a Japanese version of the album was released. It included an extra DVD with music videos and a photo gallery. It peaked at #78 on Oricon and charted for one week.`,
    ],
    tracklist: [
      "1: Intro: What am I to you",
      "2: Danger",
      "3: Hormone Jeonjaeng / War of Hormone (호르몬전쟁; Hormone War)",
      "4: Hip Hop Seongaeja / Hip Hop Phile (힙합성애자; Hip Hop Lover)",
      "5: Let Me Know",
      "6: Rain",
      "7: BTS Cypher PT.3: KILLER (ft. Supreme Boi)",
      "8: Interlude: Mwohae / Interlude: What are you doing now (뭐해; What Are You Doing)",
      "9: Haendeupon Jom Kkeojullae / Could you turn off your cell phone (핸드폰 좀 꺼줄래; Can You Turn Off Your Phone)",
      "10: Ibulkik / Embarrassed (이불킥; Blanket Kick)",
      "11: 24/7=heaven",
      "12: Yeogibwa / Look Here (여기봐; Look Here)",
      "13: 2 Haknyeon / 2nd Grade (2학년; Second Grade)",
      "14: Outro: Geuge Mari Dwae? / Outro: Do you think it makes sense? (그게 말이 돼?; Does That Make Sense?)",
    ],
  },
  {
    id: 2,
    name: "WINGS",
    releaseDate: "2016-10-10",
    imgUrl: "https://www.generasia.com/w/images/d/dd/BTS_-_WINGS.jpg",
    info: [
      `WINGS is BTS's second full-length album. The song "Pi, Ttam, Nunmul" was used as the lead track. It was released in four versions: W, I, N and G. The overall theme of the album was inspired by Hermann Hesse's "Demian", which deals with temptation and growth. WINGS is their first album to achieve #1 on the Gaon Yearly Charts.`,
      `A Japanese version of the album, titled WINGS (Japanese Edition), was released on March 2017. This version included an extra DVD. It peaked at #57 on Oricon charts and charted for five weeks.`,
    ],
    tracklist: [
      "1: Intro: Boy Meets Evil",
      "2: Pi, Ttam, Nunmul / Blood Sweat & Tears (피, 땀, 눈물, Blood, Sweat, Tears)",
      "3: Begin",
      "4: Lie",
      "5: Stigma",
      "6: First Love",
      "7: Reflection",
      "8: MAMA",
      "9: Awake",
      "10: Lost",
      "11: BTS Cypher 4",
      "12: Am I Wrong",
      "13: 21 Segi Sonyeo / 21st Century Girls (21 세기 소녀, 21st Century Girls)",
      "14: Dul! Set! (Geuraedo Joeun Nari Deo Mankireul) / 2! 3! (둘! 셋! (그래도 좋은 날이 더 많기를), Two! Three! (Still Wishing There Will Be Better Days))",
      "15: Interlude: Wings",
    ],
  },
  {
    id: 3,
    name: "Love Yourself Jeon 'Tear' (Love Yourself 轉 'Tear'; Twist)",
    releaseDate: "2018-05-18",
    imgUrl:
      "https://www.generasia.com/w/images/1/18/BTS_-_Love_Yourself_Tear.jpg",
    info: [
      `LOVE YOURSELF Jeon 'Tear' is the fourth full-length album released by BTS, and the second part of the "Love Yourself" trilogy. The song "FAKE LOVE" was used as the lead track.`,
      `Despite being a Korean release, the album is certified Gold by RIAJ for shipment of 100,000 copies.`,
    ],
    tracklist: [
      "1: Intro : Singularity",
      "2: FAKE LOVE",
      "3: Jeonhaji Mothan Jinsim / The Truth Untold (Feat. Steve Aoki) (전하지 못한 진심; The untold truth)",
      "4: 134340",
      "5: Nagwon / Paradise (낙원; Paradise)",
      "6: Love Maze",
      "7: Magic Shop",
      "8: Airplane pt.2",
      "9: Anpanman",
      "10: So What",
      "11: Outro : Tear",
    ],
  },
  {
    id: 4,
    name: "Map of the Soul: 7",
    releaseDate: "2020-02-21",
    imgUrl:
      "https://www.generasia.com/w/images/9/9a/BTS_-_Map_of_the_Soul_7.jpg",
    info: [
      `MAP OF THE SOUL: 7 is the sixth full-length album released by BTS, and the second part of the "Map of the Soul" trilogy. It was awarded the quadruple million certification by Gaon Chart, the first album to pass this threshold, becoming the best-selling album in South Korea. The song "Black Swan" was the first to be released on digital platforms, but the song "ON" was used as the lead track.`,
      `MAP OF THE SOUL: 7 was the most sold album in Korean history, certified 4xMillion by Gaon for over 4,000,000 sales. It was also the most sold album of 2020, with more than 6,5 million sales.`,
    ],
    tracklist: [
      "1: Intro: Persona",
      "2: Jageun Geotdeureul Wihan Si (Boy with Luv) (Feat. Halsey) (작은 것들을 위한 시)",
      "3: Make It Right",
      "4: Jamais Vu (Fr: Never Seen)",
      "5: Dionysus",
      "6: Interlude: Shadow",
      "7: Black Swan",
      "8: Filter",
      "9: Sicha (My Time) (시차; Parallax)",
      "10: Louder than bombs",
      "11: ON",
      "12: UGH! (욱)",
      "13: 00:00 (Zero O'Clock)",
      "14: Inner Child",
      "15: Chingu (친구; Friend)",
      "16: Moon",
      "17: Respect",
      "18: We are Bulletproof: the Eternal",
      "19: Outro: Ego",
      "20: ON (Feat. Sia)",
    ],
  },
];

export default data;
