const missing = [
  {
    id: 16,
    name: "O!RUL8,2?",
    releaseDate: "2013-09-06",
    imgUrl: "https://www.generasia.com/w/images/f/f1/ORUL82.jpg",
    info: [
      `"O!RUL8,2?" (OH! ARE YOU LATE TOO?) is BTS' first mini-album. "N.O" was used as the lead track and "Jingyeogui Bangtan" as the follow-up track. It debuted and peaked at #4 on the Gaon Weekly Chart.`,
    ],
    tracklist: [
      "1: Intro: O!RUL8,2?",
      "2: N.O",
      "3: We On",
      "4: Skit: R U Happy Now?",
      "5: If I Ruled the World",
      "6: Coffee",
      "7: BTS Cypher PT.1",
      "8: Jingyeogui Bangtan / Attack on Bangtan (진격의 방탄; Attack on Bangtan)",
      "9: Paldogangsan (팔도강산; Strong Arm)",
      "10: OUTRO: LUV IN SKOOL",
    ],
  },
  {
    id: 17,
    name: "SKOOL LUV AFFAIR SPECIAL ADDITION",
    releaseDate: "2014-05-15",
    imgUrl:
      "https://www.generasia.com/w/images/8/88/BTS_-_Skool_Luv_Affair_Special.jpg",
    info: [
      `SKOOL LUV AFFAIR SPECIAL ADDITION is an album released by BTS. It's was released three months after their mini-album SKOOL LUV AFFAIR. It includes their second mini-album tracklist as well as the new tracks "Miss Right," which was used as the title track, and "Johayo (Slow Jam Remix)" as well as six intrumentals. The mini-album came with a 100-page photobook, a randomly selected photo card, and a DVD containing their mini-album showcase, showcase making of, interview, "Sangnamja (Boy In Luv)" behind-the-scenes and "Haruman" MV making of.`,
      `In 2020, Big Hit Entertainment made a survey asking which of BTS's discontinued releases would be more wanted to be again available for sale. SKOOL LUV AFFAIR SPECIAL ADDITION came first in the pool, and was re-released on October 13th, 2020. It charted #3 on Oricon weekly charts.`,
    ],
    tracklist: [
      "1: Miss Right",
      "2: Johayo / Like (Slow Jam Remix) (좋아요; Good)",
      "3: Intro: Skool Luv Affair",
      "4: Sangnamja (Boy In Luv) / Boy In Luv (상남자; Most Masculine Man)",
      "5: Skit: Soulmate",
      "6: Eodieseo Watneunji / Where You From (어디에서 왔는지; Where Did You Come From)",
      "7: Haruman / Just One Day (하루만; Just One Day)",
      "8: Tomorrow",
      "9: BTS Cypher Pt. 2: Triptych",
      "10: Deunggor Beureikeo / Spine Breaker (등골 브레이커; Spine Breaker)",
      "11: JUMP",
      "12: Outro: Propose",
      "13: Sangnamja (Boy In Luv) (Instrumental)",
      "14: Eodieseo Watneunji (Instrumental)",
      "15: Haruman (Instrumental)",
      "16: Tomorrow (Instrumental)",
      "17: Deunggor Beureikeo (Instrumental)",
      "18: JUMP (Instrumental)",
    ],
  },
  {
    id: 18,
    name: "HYYH: Young Forever (화양연화: Young Forever; The Most Beautiful Moment in Life: Young Forever)",
    releaseDate: "2016-05-02",
    imgUrl:
      "https://www.generasia.com/w/images/2/25/BTS_-_Hwayang_Yeonhwa_Young_Forever_digital.jpg",
    info: [
      `Hwayang Yeonhwa: Young Forever is a special album released by BTS. The album is comprised of songs from both mini-albums Hwayang Yeonhwa pt. 1 and Hwayang Yeonhwa pt. 2. The song "Bultaoreune (FIRE)" was used as the lead track.`,
    ],
    version: "?",
    tracklist: [
      "Disc 1:",
      "1: INTRO: Hwayang Yeonhwa / The most beautiful moment in life (화양연화)",
      "2: I NEED U",
      "3: Jabajwo (Hold Me Tight) / Hold Me Tight (잡아줘; Catch Me)",
      "4: Goyeop / Autumn Leaves (고엽 ; Dead Leaves)",
      "5: Butterfly prologue mix",
      "6: RUN",
      "7: Ma City",
      "8: Baepsae / Silver Spoon (뱁새)",
      "9: Jjeoreo / DOPE (쩔어; Best)",
      "10: Bultaoreune (FIRE) / Burning Up (불타오르네 (FIRE))",
      "11: Save ME",
      "12: EPILOGUE: Young Forever",
      "Disc 2:",
      "1: Converse High",
      "2: Isa / Moving On (이사; Move)",
      "3: Whalien 52",
      "4: Butterfly",
      "5: House OF Cards (full length edition)",
      "6: Love is not over (full length edition)",
      "7: I NEED U urban mix",
      "8: I NEED U remix",
      "9: RUN ballad mix",
      "10: RUN (alternative mix)",
      "11: Butterfly (alternative mix)",
    ],
  },
  {
    id: 19,
    name: "Butter",
    releaseDate: "2021-07-09",
    imgUrl: "https://www.generasia.com/w/images/1/10/bts_butter_dig.jpg",
    info: [
      `"Butter" is a digital single released by BTS. It's their second song performed in English, with Dynamite being the first. It was first released as a digital single, with a physical edition released later on June 9th. The physical single was released in two versions, 'Cream' and 'Peaches', with the difference between the two resting on the contents of the package; if bought through their platform weverse, it would come with an additional postcard for each version. The B-side of the physical release, "Permission to Dance", was co-composed by English singer-songwriter Ed Sheeran.`,
    ],
    version: "?",
    tracklist: [
      "1: Butter",
      "2: Permission to Dance",
      "3: Butter (Instrumental)",
      "4: Permission to Dance (Instrumental)",
    ],
  },
];

export default missing;
